tasty_bytes:
  target: dev
  outputs:
    dev:
      account: '_'
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: dev
      role: DBT_CI_ROLE
      type: snowflake
      warehouse: TRANSFORMING
      user: '_'
      threads: 8
    prod:
      account: '_'
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: prod
      role: DBT_CI_ROLE
      type: snowflake
      warehouse: TRANSFORMING
      user: '_'
      threads: 8