tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: transformer
      database: tasty_bytes_dbt_db_rf
      schema: dev
      warehouse: TRANSFORMING
      threads: 8
    prod:
      type: snowflake
      role: TRANSFORMER
      database: TASTY_BYTES_DBT_DB_RF
      schema: prod
      warehouse: TRANSFORMING
      threads: 8
